name: Run packer build on a template file

on:
  push:
    branches: [main]
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: packer validate
        uses: docker://hashicorp/packer:latest
        with:
          args: validate packer-template.json
      - name: packer build
        uses: docker://hashicorp/packer:latest
        with:
          args: build packer-template.json
        env:
          ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
          ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
          ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
          ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
          MANAGED_IMAGE_NAME: ${{secrets.MANAGED_IMAGE_NAME}}
          RESOURCE_GROUP_NAME: ${{secrets.RESOURCE_GROUP_NAME}} 
