name: Run packer build on a template file

on:
  push:
    branches:
        - 'master'
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Packer build
        uses: riznob/packer-build-action@v1.1
        with:
          templateFile: 'packer-template.json'
          varFile: 'packer-vars.json'
          workingDir: '.'
        env:
          ARM_CLIENT_ID: ${{secrets.TF_ARM_CLIENT_ID}}
          ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
          ARM_SUBSCRIPTION_ID: ${{secrets.TF_ARM_SUBSCRIPTION_ID}}
          ARM_TENANT_ID: ${{secrets.TF_ARM_TENANT_ID}}
